// import { ibmMono } from "./ui/fonts";
// import "./globals.css";
// import { CartProvider } from "@/components/context/CartContext";
// import Head from "next/head";
// export const metadata = {
//   title: "Eeva",
//   description: "Generated by create next app",
//   // themeColor: "#182025", // color para barra superior en móviles
//   icons: {
//     icon: '/e4.svg', // Ruta al archivo SVG en la carpeta public
//   },
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <Head>
//         <meta name="google-site-verification" content="-aSvPMVt_0To09-nAayMutsKf4wXugkmApyPYVNsaxY" />
//       </Head>
//       <body className={`${ibmMono.className} antialiased bg-[#182025]`}>
//         <CartProvider>{children}</CartProvider>
//       </body>
//     </html>
//   );
// }

import { ibmMono } from "./ui/fonts";
import "./globals.css";
import { CartProvider } from "@/components/context/CartContext";

export const metadata = {
  title: "Eeva",
  description: "Generated by create next app",
  icons: {
    icon: "/e4.svg",
  },
  verification: {
    google: "-aSvPMVt_0To09-nAayMutsKf4wXugkmApyPYVNsaxY", // Agrega la verificación aquí
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Alternativa: Agrega el meta tag directamente en <head> */}
        <meta name="google-site-verification" content="-aSvPMVt_0To09-nAayMutsKf4wXugkmApyPYVNsaxY" />
      </head>
      <body className={`${ibmMono.className} antialiased bg-[#182025]`}>
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}