import { ibmMono } from "./ui/fonts"; 
import "./globals.css";



export const metadata = {
  title: "Eeva",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body 
        className={`${ibmMono.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
