import { ibmMono } from "./ui/fonts";
import "./globals.css";
import { CartProvider } from "@/components/context/CartContext";

export const metadata = {
  title: "Eeva",
  description: "Generated by create next app",
  // themeColor: "#182025", // Color para barra superior en móviles (descomentado si lo necesitas)

  icons: {
    icon: [
      { url: '/logo.ico', sizes: '16x16', type: 'image/ico' },
      { url: '/logo.ico', sizes: '32x32', type: 'image/ico' },
      { url: '/logo.ico', sizes: '64x64', type: 'image/ico' },
      { url: '/logo.ico' }, // Favicon principal en formato .ico
    ],
    apple: '/logo.ico', // Ícono para dispositivos Apple (180x180px recomendado)
    shortcut: '/logo.ico', // Ícono para accesos directos
  },
  other: {
    "google-site-verification": "-aSvPMVt_0To09-nAayMutsKf4wXugkmApyPYVNsaxY",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${ibmMono.className} antialiased bg-[#182025]`}>
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
